// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	mail "boilerplate/internal/pkg/clients/mail"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// Client is an autogenerated mock type for the Client type
type Client struct {
	mock.Mock
}

type Client_Expecter struct {
	mock *mock.Mock
}

func (_m *Client) EXPECT() *Client_Expecter {
	return &Client_Expecter{mock: &_m.Mock}
}

// Send provides a mock function with given fields: ctx, to, subject, body, attachments
func (_m *Client) Send(ctx context.Context, to string, subject string, body string, attachments []*mail.Attachment) error {
	ret := _m.Called(ctx, to, subject, body, attachments)

	if len(ret) == 0 {
		panic("no return value specified for Send")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, []*mail.Attachment) error); ok {
		r0 = rf(ctx, to, subject, body, attachments)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Client_Send_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Send'
type Client_Send_Call struct {
	*mock.Call
}

// Send is a helper method to define mock.On call
//   - ctx context.Context
//   - to string
//   - subject string
//   - body string
//   - attachments []*mail.Attachment
func (_e *Client_Expecter) Send(ctx interface{}, to interface{}, subject interface{}, body interface{}, attachments interface{}) *Client_Send_Call {
	return &Client_Send_Call{Call: _e.mock.On("Send", ctx, to, subject, body, attachments)}
}

func (_c *Client_Send_Call) Run(run func(ctx context.Context, to string, subject string, body string, attachments []*mail.Attachment)) *Client_Send_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string), args[4].([]*mail.Attachment))
	})
	return _c
}

func (_c *Client_Send_Call) Return(_a0 error) *Client_Send_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Client_Send_Call) RunAndReturn(run func(context.Context, string, string, string, []*mail.Attachment) error) *Client_Send_Call {
	_c.Call.Return(run)
	return _c
}

// NewClient creates a new instance of Client. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *Client {
	mock := &Client{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
