// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	users "boilerplate/internal/services/users"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

type Service_Expecter struct {
	mock *mock.Mock
}

func (_m *Service) EXPECT() *Service_Expecter {
	return &Service_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, req
func (_m *Service) Create(ctx context.Context, req *users.UserCreateRequest) (*users.User, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *users.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *users.UserCreateRequest) (*users.User, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *users.UserCreateRequest) *users.User); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*users.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *users.UserCreateRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Service_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type Service_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - req *users.UserCreateRequest
func (_e *Service_Expecter) Create(ctx interface{}, req interface{}) *Service_Create_Call {
	return &Service_Create_Call{Call: _e.mock.On("Create", ctx, req)}
}

func (_c *Service_Create_Call) Run(run func(ctx context.Context, req *users.UserCreateRequest)) *Service_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*users.UserCreateRequest))
	})
	return _c
}

func (_c *Service_Create_Call) Return(_a0 *users.User, _a1 error) *Service_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Service_Create_Call) RunAndReturn(run func(context.Context, *users.UserCreateRequest) (*users.User, error)) *Service_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *Service) Delete(ctx context.Context, id int) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Service_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type Service_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *Service_Expecter) Delete(ctx interface{}, id interface{}) *Service_Delete_Call {
	return &Service_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *Service_Delete_Call) Run(run func(ctx context.Context, id int)) *Service_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *Service_Delete_Call) Return(_a0 error) *Service_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Service_Delete_Call) RunAndReturn(run func(context.Context, int) error) *Service_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, id
func (_m *Service) Get(ctx context.Context, id int) (*users.User, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *users.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (*users.User, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) *users.User); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*users.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Service_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type Service_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *Service_Expecter) Get(ctx interface{}, id interface{}) *Service_Get_Call {
	return &Service_Get_Call{Call: _e.mock.On("Get", ctx, id)}
}

func (_c *Service_Get_Call) Run(run func(ctx context.Context, id int)) *Service_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *Service_Get_Call) Return(_a0 *users.User, _a1 error) *Service_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Service_Get_Call) RunAndReturn(run func(context.Context, int) (*users.User, error)) *Service_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Search provides a mock function with given fields: ctx, req
func (_m *Service) Search(ctx context.Context, req *users.UserSearchRequest) (*users.UserSearchResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Search")
	}

	var r0 *users.UserSearchResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *users.UserSearchRequest) (*users.UserSearchResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *users.UserSearchRequest) *users.UserSearchResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*users.UserSearchResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *users.UserSearchRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Service_Search_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Search'
type Service_Search_Call struct {
	*mock.Call
}

// Search is a helper method to define mock.On call
//   - ctx context.Context
//   - req *users.UserSearchRequest
func (_e *Service_Expecter) Search(ctx interface{}, req interface{}) *Service_Search_Call {
	return &Service_Search_Call{Call: _e.mock.On("Search", ctx, req)}
}

func (_c *Service_Search_Call) Run(run func(ctx context.Context, req *users.UserSearchRequest)) *Service_Search_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*users.UserSearchRequest))
	})
	return _c
}

func (_c *Service_Search_Call) Return(_a0 *users.UserSearchResponse, _a1 error) *Service_Search_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Service_Search_Call) RunAndReturn(run func(context.Context, *users.UserSearchRequest) (*users.UserSearchResponse, error)) *Service_Search_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, req
func (_m *Service) Update(ctx context.Context, req *users.UserUpdateRequest) (*users.User, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *users.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *users.UserUpdateRequest) (*users.User, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *users.UserUpdateRequest) *users.User); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*users.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *users.UserUpdateRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Service_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type Service_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - req *users.UserUpdateRequest
func (_e *Service_Expecter) Update(ctx interface{}, req interface{}) *Service_Update_Call {
	return &Service_Update_Call{Call: _e.mock.On("Update", ctx, req)}
}

func (_c *Service_Update_Call) Run(run func(ctx context.Context, req *users.UserUpdateRequest)) *Service_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*users.UserUpdateRequest))
	})
	return _c
}

func (_c *Service_Update_Call) Return(_a0 *users.User, _a1 error) *Service_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Service_Update_Call) RunAndReturn(run func(context.Context, *users.UserUpdateRequest) (*users.User, error)) *Service_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewService creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewService(t interface {
	mock.TestingT
	Cleanup(func())
}) *Service {
	mock := &Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
