// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	net "net"
)

// BrokerServer is an autogenerated mock type for the BrokerServer type
type BrokerServer struct {
	mock.Mock
}

type BrokerServer_Expecter struct {
	mock *mock.Mock
}

func (_m *BrokerServer) EXPECT() *BrokerServer_Expecter {
	return &BrokerServer_Expecter{mock: &_m.Mock}
}

// GetConn provides a mock function with no fields
func (_m *BrokerServer) GetConn() (net.Conn, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetConn")
	}

	var r0 net.Conn
	var r1 error
	if rf, ok := ret.Get(0).(func() (net.Conn, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() net.Conn); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(net.Conn)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// BrokerServer_GetConn_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetConn'
type BrokerServer_GetConn_Call struct {
	*mock.Call
}

// GetConn is a helper method to define mock.On call
func (_e *BrokerServer_Expecter) GetConn() *BrokerServer_GetConn_Call {
	return &BrokerServer_GetConn_Call{Call: _e.mock.On("GetConn")}
}

func (_c *BrokerServer_GetConn_Call) Run(run func()) *BrokerServer_GetConn_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *BrokerServer_GetConn_Call) Return(_a0 net.Conn, _a1 error) *BrokerServer_GetConn_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *BrokerServer_GetConn_Call) RunAndReturn(run func() (net.Conn, error)) *BrokerServer_GetConn_Call {
	_c.Call.Return(run)
	return _c
}

// Start provides a mock function with no fields
func (_m *BrokerServer) Start() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// BrokerServer_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type BrokerServer_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
func (_e *BrokerServer_Expecter) Start() *BrokerServer_Start_Call {
	return &BrokerServer_Start_Call{Call: _e.mock.On("Start")}
}

func (_c *BrokerServer_Start_Call) Run(run func()) *BrokerServer_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *BrokerServer_Start_Call) Return(_a0 error) *BrokerServer_Start_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *BrokerServer_Start_Call) RunAndReturn(run func() error) *BrokerServer_Start_Call {
	_c.Call.Return(run)
	return _c
}

// Stop provides a mock function with no fields
func (_m *BrokerServer) Stop() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Stop")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// BrokerServer_Stop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stop'
type BrokerServer_Stop_Call struct {
	*mock.Call
}

// Stop is a helper method to define mock.On call
func (_e *BrokerServer_Expecter) Stop() *BrokerServer_Stop_Call {
	return &BrokerServer_Stop_Call{Call: _e.mock.On("Stop")}
}

func (_c *BrokerServer_Stop_Call) Run(run func()) *BrokerServer_Stop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *BrokerServer_Stop_Call) Return(_a0 error) *BrokerServer_Stop_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *BrokerServer_Stop_Call) RunAndReturn(run func() error) *BrokerServer_Stop_Call {
	_c.Call.Return(run)
	return _c
}

// NewBrokerServer creates a new instance of BrokerServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBrokerServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *BrokerServer {
	mock := &BrokerServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
