// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// BrokerHandler is an autogenerated mock type for the BrokerHandler type
type BrokerHandler struct {
	mock.Mock
}

type BrokerHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *BrokerHandler) EXPECT() *BrokerHandler_Expecter {
	return &BrokerHandler_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx, subject, data
func (_m *BrokerHandler) Execute(ctx context.Context, subject string, data []byte) error {
	ret := _m.Called(ctx, subject, data)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []byte) error); ok {
		r0 = rf(ctx, subject, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// BrokerHandler_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type BrokerHandler_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - subject string
//   - data []byte
func (_e *BrokerHandler_Expecter) Execute(ctx interface{}, subject interface{}, data interface{}) *BrokerHandler_Execute_Call {
	return &BrokerHandler_Execute_Call{Call: _e.mock.On("Execute", ctx, subject, data)}
}

func (_c *BrokerHandler_Execute_Call) Run(run func(ctx context.Context, subject string, data []byte)) *BrokerHandler_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].([]byte))
	})
	return _c
}

func (_c *BrokerHandler_Execute_Call) Return(_a0 error) *BrokerHandler_Execute_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *BrokerHandler_Execute_Call) RunAndReturn(run func(context.Context, string, []byte) error) *BrokerHandler_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewBrokerHandler creates a new instance of BrokerHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBrokerHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *BrokerHandler {
	mock := &BrokerHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
