// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	model "boilerplate/internal/model"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// BrokerClient is an autogenerated mock type for the BrokerClient type
type BrokerClient struct {
	mock.Mock
}

type BrokerClient_Expecter struct {
	mock *mock.Mock
}

func (_m *BrokerClient) EXPECT() *BrokerClient_Expecter {
	return &BrokerClient_Expecter{mock: &_m.Mock}
}

// Close provides a mock function with no fields
func (_m *BrokerClient) Close() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// BrokerClient_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type BrokerClient_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *BrokerClient_Expecter) Close() *BrokerClient_Close_Call {
	return &BrokerClient_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *BrokerClient_Close_Call) Run(run func()) *BrokerClient_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *BrokerClient_Close_Call) Return(_a0 error) *BrokerClient_Close_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *BrokerClient_Close_Call) RunAndReturn(run func() error) *BrokerClient_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Publish provides a mock function with given fields: ctx, subject, key, data
func (_m *BrokerClient) Publish(ctx context.Context, subject string, key any, data any) error {
	ret := _m.Called(ctx, subject, key, data)

	if len(ret) == 0 {
		panic("no return value specified for Publish")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, any, any) error); ok {
		r0 = rf(ctx, subject, key, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// BrokerClient_Publish_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Publish'
type BrokerClient_Publish_Call struct {
	*mock.Call
}

// Publish is a helper method to define mock.On call
//   - ctx context.Context
//   - subject string
//   - key any
//   - data any
func (_e *BrokerClient_Expecter) Publish(ctx interface{}, subject interface{}, key interface{}, data interface{}) *BrokerClient_Publish_Call {
	return &BrokerClient_Publish_Call{Call: _e.mock.On("Publish", ctx, subject, key, data)}
}

func (_c *BrokerClient_Publish_Call) Run(run func(ctx context.Context, subject string, key any, data any)) *BrokerClient_Publish_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(any), args[3].(any))
	})
	return _c
}

func (_c *BrokerClient_Publish_Call) Return(_a0 error) *BrokerClient_Publish_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *BrokerClient_Publish_Call) RunAndReturn(run func(context.Context, string, any, any) error) *BrokerClient_Publish_Call {
	_c.Call.Return(run)
	return _c
}

// Subscribe provides a mock function with given fields: ctx, consumerName, subjects, handler
func (_m *BrokerClient) Subscribe(ctx context.Context, consumerName string, subjects []string, handler model.BrokerHandler) error {
	ret := _m.Called(ctx, consumerName, subjects, handler)

	if len(ret) == 0 {
		panic("no return value specified for Subscribe")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []string, model.BrokerHandler) error); ok {
		r0 = rf(ctx, consumerName, subjects, handler)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// BrokerClient_Subscribe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Subscribe'
type BrokerClient_Subscribe_Call struct {
	*mock.Call
}

// Subscribe is a helper method to define mock.On call
//   - ctx context.Context
//   - consumerName string
//   - subjects []string
//   - handler model.BrokerHandler
func (_e *BrokerClient_Expecter) Subscribe(ctx interface{}, consumerName interface{}, subjects interface{}, handler interface{}) *BrokerClient_Subscribe_Call {
	return &BrokerClient_Subscribe_Call{Call: _e.mock.On("Subscribe", ctx, consumerName, subjects, handler)}
}

func (_c *BrokerClient_Subscribe_Call) Run(run func(ctx context.Context, consumerName string, subjects []string, handler model.BrokerHandler)) *BrokerClient_Subscribe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].([]string), args[3].(model.BrokerHandler))
	})
	return _c
}

func (_c *BrokerClient_Subscribe_Call) Return(_a0 error) *BrokerClient_Subscribe_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *BrokerClient_Subscribe_Call) RunAndReturn(run func(context.Context, string, []string, model.BrokerHandler) error) *BrokerClient_Subscribe_Call {
	_c.Call.Return(run)
	return _c
}

// NewBrokerClient creates a new instance of BrokerClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBrokerClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *BrokerClient {
	mock := &BrokerClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
