// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// BrokerConsumer is an autogenerated mock type for the BrokerConsumer type
type BrokerConsumer struct {
	mock.Mock
}

type BrokerConsumer_Expecter struct {
	mock *mock.Mock
}

func (_m *BrokerConsumer) EXPECT() *BrokerConsumer_Expecter {
	return &BrokerConsumer_Expecter{mock: &_m.Mock}
}

// DLQTopic provides a mock function with no fields
func (_m *BrokerConsumer) DLQTopic() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for DLQTopic")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// BrokerConsumer_DLQTopic_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DLQTopic'
type BrokerConsumer_DLQTopic_Call struct {
	*mock.Call
}

// DLQTopic is a helper method to define mock.On call
func (_e *BrokerConsumer_Expecter) DLQTopic() *BrokerConsumer_DLQTopic_Call {
	return &BrokerConsumer_DLQTopic_Call{Call: _e.mock.On("DLQTopic")}
}

func (_c *BrokerConsumer_DLQTopic_Call) Run(run func()) *BrokerConsumer_DLQTopic_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *BrokerConsumer_DLQTopic_Call) Return(_a0 string) *BrokerConsumer_DLQTopic_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *BrokerConsumer_DLQTopic_Call) RunAndReturn(run func() string) *BrokerConsumer_DLQTopic_Call {
	_c.Call.Return(run)
	return _c
}

// Description provides a mock function with no fields
func (_m *BrokerConsumer) Description() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Description")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// BrokerConsumer_Description_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Description'
type BrokerConsumer_Description_Call struct {
	*mock.Call
}

// Description is a helper method to define mock.On call
func (_e *BrokerConsumer_Expecter) Description() *BrokerConsumer_Description_Call {
	return &BrokerConsumer_Description_Call{Call: _e.mock.On("Description")}
}

func (_c *BrokerConsumer_Description_Call) Run(run func()) *BrokerConsumer_Description_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *BrokerConsumer_Description_Call) Return(_a0 string) *BrokerConsumer_Description_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *BrokerConsumer_Description_Call) RunAndReturn(run func() string) *BrokerConsumer_Description_Call {
	_c.Call.Return(run)
	return _c
}

// HandleMessage provides a mock function with given fields: ctx, subject, data
func (_m *BrokerConsumer) HandleMessage(ctx context.Context, subject string, data []byte) error {
	ret := _m.Called(ctx, subject, data)

	if len(ret) == 0 {
		panic("no return value specified for HandleMessage")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []byte) error); ok {
		r0 = rf(ctx, subject, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// BrokerConsumer_HandleMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleMessage'
type BrokerConsumer_HandleMessage_Call struct {
	*mock.Call
}

// HandleMessage is a helper method to define mock.On call
//   - ctx context.Context
//   - subject string
//   - data []byte
func (_e *BrokerConsumer_Expecter) HandleMessage(ctx interface{}, subject interface{}, data interface{}) *BrokerConsumer_HandleMessage_Call {
	return &BrokerConsumer_HandleMessage_Call{Call: _e.mock.On("HandleMessage", ctx, subject, data)}
}

func (_c *BrokerConsumer_HandleMessage_Call) Run(run func(ctx context.Context, subject string, data []byte)) *BrokerConsumer_HandleMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].([]byte))
	})
	return _c
}

func (_c *BrokerConsumer_HandleMessage_Call) Return(_a0 error) *BrokerConsumer_HandleMessage_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *BrokerConsumer_HandleMessage_Call) RunAndReturn(run func(context.Context, string, []byte) error) *BrokerConsumer_HandleMessage_Call {
	_c.Call.Return(run)
	return _c
}

// MainTopic provides a mock function with no fields
func (_m *BrokerConsumer) MainTopic() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for MainTopic")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// BrokerConsumer_MainTopic_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MainTopic'
type BrokerConsumer_MainTopic_Call struct {
	*mock.Call
}

// MainTopic is a helper method to define mock.On call
func (_e *BrokerConsumer_Expecter) MainTopic() *BrokerConsumer_MainTopic_Call {
	return &BrokerConsumer_MainTopic_Call{Call: _e.mock.On("MainTopic")}
}

func (_c *BrokerConsumer_MainTopic_Call) Run(run func()) *BrokerConsumer_MainTopic_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *BrokerConsumer_MainTopic_Call) Return(_a0 string) *BrokerConsumer_MainTopic_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *BrokerConsumer_MainTopic_Call) RunAndReturn(run func() string) *BrokerConsumer_MainTopic_Call {
	_c.Call.Return(run)
	return _c
}

// Name provides a mock function with no fields
func (_m *BrokerConsumer) Name() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Name")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// BrokerConsumer_Name_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Name'
type BrokerConsumer_Name_Call struct {
	*mock.Call
}

// Name is a helper method to define mock.On call
func (_e *BrokerConsumer_Expecter) Name() *BrokerConsumer_Name_Call {
	return &BrokerConsumer_Name_Call{Call: _e.mock.On("Name")}
}

func (_c *BrokerConsumer_Name_Call) Run(run func()) *BrokerConsumer_Name_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *BrokerConsumer_Name_Call) Return(_a0 string) *BrokerConsumer_Name_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *BrokerConsumer_Name_Call) RunAndReturn(run func() string) *BrokerConsumer_Name_Call {
	_c.Call.Return(run)
	return _c
}

// NewBrokerConsumer creates a new instance of BrokerConsumer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBrokerConsumer(t interface {
	mock.TestingT
	Cleanup(func())
}) *BrokerConsumer {
	mock := &BrokerConsumer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
