// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	model "boilerplate/internal/model"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// BrokerClient is an autogenerated mock type for the BrokerClient type
type BrokerClient struct {
	mock.Mock
}

type BrokerClient_Expecter struct {
	mock *mock.Mock
}

func (_m *BrokerClient) EXPECT() *BrokerClient_Expecter {
	return &BrokerClient_Expecter{mock: &_m.Mock}
}

// Close provides a mock function with no fields
func (_m *BrokerClient) Close() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// BrokerClient_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type BrokerClient_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *BrokerClient_Expecter) Close() *BrokerClient_Close_Call {
	return &BrokerClient_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *BrokerClient_Close_Call) Run(run func()) *BrokerClient_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *BrokerClient_Close_Call) Return(_a0 error) *BrokerClient_Close_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *BrokerClient_Close_Call) RunAndReturn(run func() error) *BrokerClient_Close_Call {
	_c.Call.Return(run)
	return _c
}

// CreateOrUpdateTopic provides a mock function with given fields: ctx, topic
func (_m *BrokerClient) CreateOrUpdateTopic(ctx context.Context, topic model.BrokerTopic) error {
	ret := _m.Called(ctx, topic)

	if len(ret) == 0 {
		panic("no return value specified for CreateOrUpdateTopic")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, model.BrokerTopic) error); ok {
		r0 = rf(ctx, topic)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// BrokerClient_CreateOrUpdateTopic_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateOrUpdateTopic'
type BrokerClient_CreateOrUpdateTopic_Call struct {
	*mock.Call
}

// CreateOrUpdateTopic is a helper method to define mock.On call
//   - ctx context.Context
//   - topic model.BrokerTopic
func (_e *BrokerClient_Expecter) CreateOrUpdateTopic(ctx interface{}, topic interface{}) *BrokerClient_CreateOrUpdateTopic_Call {
	return &BrokerClient_CreateOrUpdateTopic_Call{Call: _e.mock.On("CreateOrUpdateTopic", ctx, topic)}
}

func (_c *BrokerClient_CreateOrUpdateTopic_Call) Run(run func(ctx context.Context, topic model.BrokerTopic)) *BrokerClient_CreateOrUpdateTopic_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.BrokerTopic))
	})
	return _c
}

func (_c *BrokerClient_CreateOrUpdateTopic_Call) Return(_a0 error) *BrokerClient_CreateOrUpdateTopic_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *BrokerClient_CreateOrUpdateTopic_Call) RunAndReturn(run func(context.Context, model.BrokerTopic) error) *BrokerClient_CreateOrUpdateTopic_Call {
	_c.Call.Return(run)
	return _c
}

// Publish provides a mock function with given fields: ctx, topic, partition, key, data
func (_m *BrokerClient) Publish(ctx context.Context, topic string, partition *int, key any, data any) error {
	ret := _m.Called(ctx, topic, partition, key, data)

	if len(ret) == 0 {
		panic("no return value specified for Publish")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *int, any, any) error); ok {
		r0 = rf(ctx, topic, partition, key, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// BrokerClient_Publish_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Publish'
type BrokerClient_Publish_Call struct {
	*mock.Call
}

// Publish is a helper method to define mock.On call
//   - ctx context.Context
//   - topic string
//   - partition *int
//   - key any
//   - data any
func (_e *BrokerClient_Expecter) Publish(ctx interface{}, topic interface{}, partition interface{}, key interface{}, data interface{}) *BrokerClient_Publish_Call {
	return &BrokerClient_Publish_Call{Call: _e.mock.On("Publish", ctx, topic, partition, key, data)}
}

func (_c *BrokerClient_Publish_Call) Run(run func(ctx context.Context, topic string, partition *int, key any, data any)) *BrokerClient_Publish_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*int), args[3].(any), args[4].(any))
	})
	return _c
}

func (_c *BrokerClient_Publish_Call) Return(_a0 error) *BrokerClient_Publish_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *BrokerClient_Publish_Call) RunAndReturn(run func(context.Context, string, *int, any, any) error) *BrokerClient_Publish_Call {
	_c.Call.Return(run)
	return _c
}

// Subscribe provides a mock function with given fields: ctx, consumerName, description, topic, handler
func (_m *BrokerClient) Subscribe(ctx context.Context, consumerName string, description string, topic model.BrokerTopic, handler model.BrokerHandler) error {
	ret := _m.Called(ctx, consumerName, description, topic, handler)

	if len(ret) == 0 {
		panic("no return value specified for Subscribe")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, model.BrokerTopic, model.BrokerHandler) error); ok {
		r0 = rf(ctx, consumerName, description, topic, handler)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// BrokerClient_Subscribe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Subscribe'
type BrokerClient_Subscribe_Call struct {
	*mock.Call
}

// Subscribe is a helper method to define mock.On call
//   - ctx context.Context
//   - consumerName string
//   - description string
//   - topic model.BrokerTopic
//   - handler model.BrokerHandler
func (_e *BrokerClient_Expecter) Subscribe(ctx interface{}, consumerName interface{}, description interface{}, topic interface{}, handler interface{}) *BrokerClient_Subscribe_Call {
	return &BrokerClient_Subscribe_Call{Call: _e.mock.On("Subscribe", ctx, consumerName, description, topic, handler)}
}

func (_c *BrokerClient_Subscribe_Call) Run(run func(ctx context.Context, consumerName string, description string, topic model.BrokerTopic, handler model.BrokerHandler)) *BrokerClient_Subscribe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(model.BrokerTopic), args[4].(model.BrokerHandler))
	})
	return _c
}

func (_c *BrokerClient_Subscribe_Call) Return(_a0 error) *BrokerClient_Subscribe_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *BrokerClient_Subscribe_Call) RunAndReturn(run func(context.Context, string, string, model.BrokerTopic, model.BrokerHandler) error) *BrokerClient_Subscribe_Call {
	_c.Call.Return(run)
	return _c
}

// NewBrokerClient creates a new instance of BrokerClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBrokerClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *BrokerClient {
	mock := &BrokerClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
