// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	grpc "google.golang.org/grpc"

	mock "github.com/stretchr/testify/mock"

	runtime "github.com/grpc-ecosystem/grpc-gateway/v2/runtime"
)

// GRPCHandler is an autogenerated mock type for the GRPCHandler type
type GRPCHandler struct {
	mock.Mock
}

type GRPCHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *GRPCHandler) EXPECT() *GRPCHandler_Expecter {
	return &GRPCHandler_Expecter{mock: &_m.Mock}
}

// RegisterGRPCServer provides a mock function with given fields: server
func (_m *GRPCHandler) RegisterGRPCServer(server *grpc.Server) {
	_m.Called(server)
}

// GRPCHandler_RegisterGRPCServer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterGRPCServer'
type GRPCHandler_RegisterGRPCServer_Call struct {
	*mock.Call
}

// RegisterGRPCServer is a helper method to define mock.On call
//   - server *grpc.Server
func (_e *GRPCHandler_Expecter) RegisterGRPCServer(server interface{}) *GRPCHandler_RegisterGRPCServer_Call {
	return &GRPCHandler_RegisterGRPCServer_Call{Call: _e.mock.On("RegisterGRPCServer", server)}
}

func (_c *GRPCHandler_RegisterGRPCServer_Call) Run(run func(server *grpc.Server)) *GRPCHandler_RegisterGRPCServer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*grpc.Server))
	})
	return _c
}

func (_c *GRPCHandler_RegisterGRPCServer_Call) Return() *GRPCHandler_RegisterGRPCServer_Call {
	_c.Call.Return()
	return _c
}

func (_c *GRPCHandler_RegisterGRPCServer_Call) RunAndReturn(run func(*grpc.Server)) *GRPCHandler_RegisterGRPCServer_Call {
	_c.Run(run)
	return _c
}

// RegisterHTTPHandler provides a mock function with given fields: ctx, mux, conn
func (_m *GRPCHandler) RegisterHTTPHandler(ctx context.Context, mux *runtime.ServeMux, conn *grpc.ClientConn) error {
	ret := _m.Called(ctx, mux, conn)

	if len(ret) == 0 {
		panic("no return value specified for RegisterHTTPHandler")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *runtime.ServeMux, *grpc.ClientConn) error); ok {
		r0 = rf(ctx, mux, conn)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GRPCHandler_RegisterHTTPHandler_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterHTTPHandler'
type GRPCHandler_RegisterHTTPHandler_Call struct {
	*mock.Call
}

// RegisterHTTPHandler is a helper method to define mock.On call
//   - ctx context.Context
//   - mux *runtime.ServeMux
//   - conn *grpc.ClientConn
func (_e *GRPCHandler_Expecter) RegisterHTTPHandler(ctx interface{}, mux interface{}, conn interface{}) *GRPCHandler_RegisterHTTPHandler_Call {
	return &GRPCHandler_RegisterHTTPHandler_Call{Call: _e.mock.On("RegisterHTTPHandler", ctx, mux, conn)}
}

func (_c *GRPCHandler_RegisterHTTPHandler_Call) Run(run func(ctx context.Context, mux *runtime.ServeMux, conn *grpc.ClientConn)) *GRPCHandler_RegisterHTTPHandler_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*runtime.ServeMux), args[2].(*grpc.ClientConn))
	})
	return _c
}

func (_c *GRPCHandler_RegisterHTTPHandler_Call) Return(_a0 error) *GRPCHandler_RegisterHTTPHandler_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *GRPCHandler_RegisterHTTPHandler_Call) RunAndReturn(run func(context.Context, *runtime.ServeMux, *grpc.ClientConn) error) *GRPCHandler_RegisterHTTPHandler_Call {
	_c.Call.Return(run)
	return _c
}

// NewGRPCHandler creates a new instance of GRPCHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGRPCHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *GRPCHandler {
	mock := &GRPCHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
