// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"
	mock "github.com/stretchr/testify/mock"
)

// Handler is an autogenerated mock type for the Handler type
type Handler struct {
	mock.Mock
}

type Handler_Expecter struct {
	mock *mock.Mock
}

func (_m *Handler) EXPECT() *Handler_Expecter {
	return &Handler_Expecter{mock: &_m.Mock}
}

// Mount provides a mock function with given fields: router
func (_m *Handler) Mount(router *gin.RouterGroup) {
	_m.Called(router)
}

// Handler_Mount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Mount'
type Handler_Mount_Call struct {
	*mock.Call
}

// Mount is a helper method to define mock.On call
//   - router *gin.RouterGroup
func (_e *Handler_Expecter) Mount(router interface{}) *Handler_Mount_Call {
	return &Handler_Mount_Call{Call: _e.mock.On("Mount", router)}
}

func (_c *Handler_Mount_Call) Run(run func(router *gin.RouterGroup)) *Handler_Mount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gin.RouterGroup))
	})
	return _c
}

func (_c *Handler_Mount_Call) Return() *Handler_Mount_Call {
	_c.Call.Return()
	return _c
}

func (_c *Handler_Mount_Call) RunAndReturn(run func(*gin.RouterGroup)) *Handler_Mount_Call {
	_c.Run(run)
	return _c
}

// NewHandler creates a new instance of Handler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *Handler {
	mock := &Handler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
